'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30,15")>  _
        Public Property DxL_Maq1() As String
            Get
                Return CType(Me("DxL_Maq1"),String)
            End Get
            Set
                Me("DxL_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33,35")>  _
        Public Property DxR_Maq1() As String
            Get
                Return CType(Me("DxR_Maq1"),String)
            End Get
            Set
                Me("DxR_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0,65")>  _
        Public Property DyL_Maq1() As String
            Get
                Return CType(Me("DyL_Maq1"),String)
            End Get
            Set
                Me("DyL_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0,9")>  _
        Public Property DyR_Maq1() As String
            Get
                Return CType(Me("DyR_Maq1"),String)
            End Get
            Set
                Me("DyR_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property Diameter_Maq1() As String
            Get
                Return CType(Me("Diameter_Maq1"),String)
            End Get
            Set
                Me("Diameter_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property Lenght_Maq1() As String
            Get
                Return CType(Me("Lenght_Maq1"),String)
            End Get
            Set
                Me("Lenght_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Focus_Maq1() As String
            Get
                Return CType(Me("Focus_Maq1"),String)
            End Get
            Set
                Me("Focus_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1,8")>  _
        Public Property OffsetX_Maq1() As String
            Get
                Return CType(Me("OffsetX_Maq1"),String)
            End Get
            Set
                Me("OffsetX_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1,15")>  _
        Public Property OffsetY_Maq1() As String
            Get
                Return CType(Me("OffsetY_Maq1"),String)
            End Get
            Set
                Me("OffsetY_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property GainX_Maq1() As String
            Get
                Return CType(Me("GainX_Maq1"),String)
            End Get
            Set
                Me("GainX_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0,99")>  _
        Public Property GainY_Maq1() As String
            Get
                Return CType(Me("GainY_Maq1"),String)
            End Get
            Set
                Me("GainY_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180")>  _
        Public Property Rotation_Maq1() As String
            Get
                Return CType(Me("Rotation_Maq1"),String)
            End Get
            Set
                Me("Rotation_Maq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35,95")>  _
        Public Property DxL_Maq2() As String
            Get
                Return CType(Me("DxL_Maq2"),String)
            End Get
            Set
                Me("DxL_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40,5")>  _
        Public Property DxR_Maq2() As String
            Get
                Return CType(Me("DxR_Maq2"),String)
            End Get
            Set
                Me("DxR_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0,4")>  _
        Public Property DyL_Maq2() As String
            Get
                Return CType(Me("DyL_Maq2"),String)
            End Get
            Set
                Me("DyL_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0,35")>  _
        Public Property DyR_Maq2() As String
            Get
                Return CType(Me("DyR_Maq2"),String)
            End Get
            Set
                Me("DyR_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property Diameter_Maq2() As String
            Get
                Return CType(Me("Diameter_Maq2"),String)
            End Get
            Set
                Me("Diameter_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property Lenght_Maq2() As String
            Get
                Return CType(Me("Lenght_Maq2"),String)
            End Get
            Set
                Me("Lenght_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Focus_Maq2() As String
            Get
                Return CType(Me("Focus_Maq2"),String)
            End Get
            Set
                Me("Focus_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-2,95")>  _
        Public Property OffsetX_Maq2() As String
            Get
                Return CType(Me("OffsetX_Maq2"),String)
            End Get
            Set
                Me("OffsetX_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-5,05")>  _
        Public Property OffsetY_Maq2() As String
            Get
                Return CType(Me("OffsetY_Maq2"),String)
            End Get
            Set
                Me("OffsetY_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property GainX_Maq2() As String
            Get
                Return CType(Me("GainX_Maq2"),String)
            End Get
            Set
                Me("GainX_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0,998")>  _
        Public Property GainY_Maq2() As String
            Get
                Return CType(Me("GainY_Maq2"),String)
            End Get
            Set
                Me("GainY_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180,5")>  _
        Public Property Rotation_Maq2() As String
            Get
                Return CType(Me("Rotation_Maq2"),String)
            End Get
            Set
                Me("Rotation_Maq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40,75")>  _
        Public Property DxL_Maq3() As String
            Get
                Return CType(Me("DxL_Maq3"),String)
            End Get
            Set
                Me("DxL_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33,5")>  _
        Public Property DxR_Maq3() As String
            Get
                Return CType(Me("DxR_Maq3"),String)
            End Get
            Set
                Me("DxR_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0,45")>  _
        Public Property DyL_Maq3() As String
            Get
                Return CType(Me("DyL_Maq3"),String)
            End Get
            Set
                Me("DyL_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-0,6")>  _
        Public Property DyR_Maq3() As String
            Get
                Return CType(Me("DyR_Maq3"),String)
            End Get
            Set
                Me("DyR_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24")>  _
        Public Property Diameter_Maq3() As String
            Get
                Return CType(Me("Diameter_Maq3"),String)
            End Get
            Set
                Me("Diameter_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property Lenght_Maq3() As String
            Get
                Return CType(Me("Lenght_Maq3"),String)
            End Get
            Set
                Me("Lenght_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Focus_Maq3() As String
            Get
                Return CType(Me("Focus_Maq3"),String)
            End Get
            Set
                Me("Focus_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3,25")>  _
        Public Property OffsetX_Maq3() As String
            Get
                Return CType(Me("OffsetX_Maq3"),String)
            End Get
            Set
                Me("OffsetX_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-5,95")>  _
        Public Property OffsetY_Maq3() As String
            Get
                Return CType(Me("OffsetY_Maq3"),String)
            End Get
            Set
                Me("OffsetY_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property GainX_Maq3() As String
            Get
                Return CType(Me("GainX_Maq3"),String)
            End Get
            Set
                Me("GainX_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0,973")>  _
        Public Property GainY_Maq3() As String
            Get
                Return CType(Me("GainY_Maq3"),String)
            End Get
            Set
                Me("GainY_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("180,5")>  _
        Public Property Rotation_Maq3() As String
            Get
                Return CType(Me("Rotation_Maq3"),String)
            End Get
            Set
                Me("Rotation_Maq3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathMaq1() As String
            Get
                Return CType(Me("PathMaq1"),String)
            End Get
            Set
                Me("PathMaq1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathMaq2() As String
            Get
                Return CType(Me("PathMaq2"),String)
            End Get
            Set
                Me("PathMaq2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PathMaq3() As String
            Get
                Return CType(Me("PathMaq3"),String)
            End Get
            Set
                Me("PathMaq3") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CriarProjectos.My.MySettings
            Get
                Return Global.CriarProjectos.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
